### ISSUE TITLE
extreme lag while parsing docs even with low docs enabled

### ISSUE THREAD

**Issue by AlNotAlbert** [arianrhodsandlot/DevDocs-Web-Ext#33] opened 2022-04-22 00:43 UTC
Hey, the performance is significantly lower then it was before the v3 update, it takes really long time to search for even the most basic and unique functions.

https://user-images.githubusercontent.com/87888006/164574646-2cf8ffab-671b-415d-bce1-9511b30a1994.mp4

**Comment by arianrhodsandlot** [comment] 2022-04-22 15:23
Thanks for your information👏. I failed to reproduce the problem in the video, I guess that the request for documents' API is causing the lag in the video. Does this happen every time you search or only the first time?

**Comment by AlNotAlbert** [comment] 2022-04-23 21:24
it happens every time i search, I tried with more than one browser(brave, chrome, vivaldi) and operation system (windows 10 and OSX 11.6.5).

**Comment by arianrhodsandlot** [comment] 2022-04-24 09:46
Reproduced after enabling lots of documents 🤔 . I'll look into this problem and do some optimization in recent time.

**Comment by AlNotAlbert** [comment] 2022-04-24 23:26
> Reproduced after enabling lots of documents 🤔 . I'll look into this problem and do some optimization in recent time.
![29be267602ff0bb49305a00f75ab2024](https://user-images.githubusercontent.com/87888006/165001024-ec62fa65-80bc-4434-9562-fdad1b76da29.png)
these are my current docs enabled, how much is too many?

**Comment by arianrhodsandlot** [comment] 2022-05-01 09:25
> how much is too many?

It depends, since the size of documents varies. Before this perfermance issue being fixed, temporarily disabling some big documents may help. In this case, the biggest ones seems to be Rust (https://documents.devdocs.io/rust/index.json, 3.4 MB) and Qt (https://documents.devdocs.io/qt/index.json 3.6 MB).

---

A fixed version will be released these days.

**Closed** 2022-05-03 12:58 UTC
Labels: bug
